spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toby
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: dmstmddnjs32!
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace



