spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pop
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: dmstmddnjs32!

  jpa:
    hibernate:
      ddl-auto: create

#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        user_sql_comments: true



logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace





