spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # 한번에 가져오는 인쿼리의 개수 끝까지 루프를 통해 가져옴//
#    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace


